### ISSUE TITLE
ExtractStyles failure; Unrecognised input; @import  "~font-awesome/scss/_variables.scss"; 

### ISSUE THREAD

**Issue by kevzettler** [gowravshekar/font-awesome-webpack#22]
```
[1] ERROR in ../~/extract-text-webpack-plugin/loader.js?{"omit":1,"extract":true,"remove":true}!../~/style-loader!../~/css-loader!../~/less-loader!../~/font-awesome-loader/font-awesome-styles.loader.js!./font-awesome.config.js
[1] Module build failed: ModuleBuildError: Module build failed: Unrecognised input
[1]  @ /Users/kevzettler/projects/tilt/ambassador-web/config/font-awesome.config.js (line 2, column 0)
[1]  near lines:
[1]    @import          "~font-awesome/scss/_variables.scss";
[1]    $fa-font-path: "~font-awesome/fonts/";
[1]    @import "~font-awesome/scss/_mixins.scss";
[1]     at DependenciesBlock.onModuleBuildFailed (/Users/kevzettler/projects/tilt/ambassador-web/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:315:19)
[1]     at nextLoader (/Users/kevzettler/projects/tilt/ambassador-web/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:270:31)
[1]     at /Users/kevzettler/projects/tilt/ambassador-web/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
[1]     at context.callback (/Users/kevzettler/projects/tilt/ambassador-web/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
[1]     at /Users/kevzettler/projects/tilt/ambassador-web/node_modules/less-loader/index.js:68:16
[1]     at /Users/kevzettler/projects/tilt/ambassador-web/node_modules/less/lib/less/render.js:26:35
[1]     at /Users/kevzettler/projects/tilt/ambassador-web/node_modules/less/lib/less/parse.js:62:33
```

**Comment by gowravshekar** [comment]
This is less loader. For `sass` use - https://github.com/francisbesset/font-awesome-sass-loader
